server:
  port: 8180
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
  http2:
    enabled: true
  servlet:
    encoding:
      force-response: true

spring:
  application:
    name: jichul
  main:
    banner-mode: off
  messages:
    encoding: UTF-8
  output:
    ansi:
      enabled: always
  threads:
    virtual:
      enabled: true

  datasource:
    url: ENC(YxmqRj0y24PFNcUMigjGukIvKTtNC+fPCgZerNjZ8CEZhFr9ruvnjo18xUMtJL7YLF4d5cBD3MV1yFQV4VOHLFVq/MwfJvxR0crFnkdy1xXKibzHeKmpp4HWoPG+gcQyRKmcGOYxbZ6av3LlbTujEILRr5NCba5eAOjK/mAA6TI=)
    username: ENC(nokIUDMGgNG7XbF7gGBfARAevpJrk21InbtIb66AX64LbOE9OibhozLIBW8YRnx6)
    password: ENC(YRcY/ZWmkKsEoPASUs5pNRwonwdcOSFuK2mq7pH7J54zqntp0OWhAvdl5n0vheZL)
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        format_sql: false
        jdbc:
          batch_size: 50
          order_inserts: true
          order_updates: true
          time_zone: Asia/Seoul

  security:
    user:
      name: ENC(r/iF47mt9Z4raglex1oyDGkTb/vmjZacfD2cbY3QjpFQCipsWMXfxZf80TIshySe)
      password: ENC(4qF4f04i//O2WMLmTsPW+KPITH0opTi1zBHkb/mCam/Jwz7c5FWsjb7TOOcLnU2E)

  data:
    redis:
      username: ENC(FqhdpDEp4ktIV1OPSPAln69+QjKxTmerXE68NjjEw2QWBoiUdbkITpxon7DI3M+C)
      password: ENC(/A79Fm906R5h2VLMIrvQPtB3owkJbuieGYy23G97StYbHaL+NI/UWcmK4VFSZ90Pg4sbSa3sXfm5QZh9HVjlNLBruUZ4pa3zvp5V57Xv+qM=)
      host: ENC(QB4GkM7z+KcQVvPydBqIqPubPPLNR7k4uE7mnjQg00Q87eqbRsY6Lk8ZxH3DH7qEntIZlvlhoIbrUmWoZeb46dgBpEEF5DFgdE+Sh6NzmV6yILsGyThyqRBkKIMBcBhk)
      port: ENC(oreF1vULcym5uz66LUIm8bnF5jnkPlNjg6YPWciKhIUnqroBUfdO4BIQTNIzEJM2)
      lettuce:
        pool:
          min-idle: 4
          max-idle: 10
          max-active: 10
      timeout: 3000ms
      connect-timeout: 3000ms

jwt:
  access-token-expiry: 1d
  refresh-token-expiry: 7d

logging:
  level:
    root: INFO
    work.seoeungi.jichul: INFO
    org.hibernate.SQL: INFO

jasypt:
  encryptor:
    algorithm: PBEWITHHMACSHA512ANDAES_256
    key-obtention-iterations: 10000
    pool-size: 1

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    shutdown:
      access: none
    health:
      show-details: always
  metrics:
    enable:
      all: true
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true