server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
  http2:
    enabled: true
  servlet:
    encoding:
      force-response: true

spring:
  application:
    name: jichul
  main:
    banner-mode: OFF

  threads:
    virtual:
      enabled: true

  output:
    ansi:
      enabled: always

  datasource:
    url: ENC(nTVsSAH4JspTtsTD2z4Uyo1ymUIpHLQuB4EKuNyTbpyYeXv9dAHRXrk5fgN2bs2db9jOiNZuEcQA9aVznqfVRQYAs3dGGEJf+p8H6VGJMu/j05X5bW4LeofuC43YMan8L6NPin7lP2zSkCkCH6sd5QuL+Vqv8YXsA0GeWq99Ugo=)
    username: ENC(NedXiG6VzsP4Bacs6zWmMQ8rHlh5mh5ZGH+4W1khE9kA6jz5M5JmnKdgSX5YGOrD)
    password: ENC(dxczUoj6BCnUDQP8kXrTlGQyOIXsAFQWzY0jYklWkBEMI9L+4laWK6YXY9UwidiB)
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        jdbc:
          batch_size: 50
          order_inserts: true
          order_updates: true
          time_zone: Asia/Seoul

  security:
    user:
      name: ENC(1X6Y1esr40licG7FX047uqP2vAINJ/coCCeVRxli2/Ii6T3AniO4kDf1uNLlAm+z)
      password: ENC(6EgSUogcQT2hJiRpybp34V3mubbWRDVVTeuxqjj9N4wq2JgQUfP23LcR3lLtLYdu)

  data:
    redis:
      username: ENC(TP7dEJrZ48+S+oHm5OTXHVQ3liCkURl4digdQqv0Yn0VfjwqGE83mYh5e8O7CG3A)
      password: ENC(9BFhYvFUoNi8/KIntQyfdN8fnTsMFYPLhwbGhvUjo4lPf1r6G+eWHxyw6R9CwEIBtxMkKaJvFws9k5Pn58RtJMpqkT/LTIvKnt/CFMmj6WM=)
      host: ENC(63DwX3OM1v+fps8O2C+LY0JsT4FH2ODPJ2S/hj+mAvL1accFgS+JnmZBNXWkuHorAM3y+JxYPdj3QmFewgW7EQpdrBvNLhM1hAQTenui6F80WX6GTXR6L5LmQc5XFwBo)
      port: ENC(KAWjfRHgt+e/Fu3X4RwxaqL7Asro+oQo6Cxt0lrGIrEPy0rr26rJQoVnUc4FOj9S)
      timeout: 5000
      lettuce:
        pool:
          min-idle: 3
          max-idle: 10
          max-active: 10
        shutdown-timeout: 2000

jwt:
  access-token-expiry: 24h
  refresh-token-expiry: 7d

logging:
  config: classpath:/logback/spring-logback.xml

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    shutdown:
      access: none
    health:
      probes:
        enabled: true
      show-details: always
  metrics:
    enable:
      all: true
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    db:
      enabled: false
    redis:
      enabled: false
    mail:
      enabled: false
    diskSpace:
      enabled: false

jasypt:
  encryptor:
    algorithm: PBEWITHHMACSHA512ANDAES_256
    key-obtention-iterations: 10000
    pool-size: 1

third-party:
  open-exchange-rates:
    url: https://openexchangerates.org/api/latest.json
    key: ENC(WiDco/I/P+vG4HhCPOlD6zR3SjX5Cf8p7UWMo+8TU1xbAwIwfHTszH1CDEej9G/2nPIWK4fezMXuoBFkN9xzhbq8m+h7zjH2FX+ab6sIKbE=)